base: &base
  url: <%= ENV['DATABASE_URL'] %>
  database: <%= ENV.fetch('DATABASE_NAME') %>
  schema_search_path: <%= ENV['DATABASE_SEARCH_PATH'] %>
  pool: <%= ENV['DATABASE_POOL'] %>
  encoding: utf8
  adapter: postgresql
  reconnect: 'true'

test:
  <<: *base
  database: <%= "#{ENV.fetch('DATABASE_NAME')}-test" %>

development:
  <<: *base

dev_integration:
  <<: *base

qa:
  <<: *base

staging:
  <<: *base

uat:
  <<: *base

production:
  <<: *base
